# Oracle Database Connection
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=SYSTEM
spring.datasource.password=Pranav
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Keep the connection alive
spring.datasource.hikari.maximum-pool-size=5